// Terms that mean the same thing. When any term in a group appears in a session or article, every
// term in the group becomes searchable for it, so "microscopic hematuria" finds the Microhematuria
// guideline. One group per line; case and punctuation don't matter. Terms match whole words only,
// so short abbreviations like "ic" or "ud" won't fire inside longer words.
export const SYNONYMS: string[][] = [
  // Bladder and incontinence
  ["microhematuria", "microscopic hematuria", "asymptomatic microscopic hematuria", "amh"],
  ["gross hematuria", "macroscopic hematuria", "visible hematuria"],
  ["oab", "overactive bladder"],
  ["sui", "stress urinary incontinence", "stress incontinence"],
  ["uui", "urgency urinary incontinence", "urge urinary incontinence", "urge incontinence"],
  ["mui", "mixed urinary incontinence", "mixed incontinence"],
  ["ui", "urinary incontinence"],
  ["luts", "lower urinary tract symptoms"],
  ["lut", "lower urinary tract"],
  ["lutd", "lower urinary tract dysfunction"],
  ["nlutd", "neurogenic lower urinary tract dysfunction", "neurogenic bladder"],
  ["urinary retention", "voiding dysfunction", "incomplete bladder emptying"],
  ["pvr", "post void residual", "postvoid residual"],
  ["isc", "cic", "intermittent catheterization", "self catheterization", "clean intermittent catheterization"],
  ["bps", "ic", "bps ic", "pbs", "bladder pain syndrome", "interstitial cystitis", "painful bladder syndrome"],
  ["uti", "urinary tract infection", "ruti", "recurrent uti"],
  ["asb", "asymptomatic bacteriuria"],
  // Prolapse
  ["pop", "pelvic organ prolapse"],
  ["pop q", "popq", "pelvic organ prolapse quantification"],
  ["usls", "uterosacral ligament suspension", "uterosacral suspension"],
  ["ssls", "sacrospinous ligament suspension", "sacrospinous ligament fixation", "sacrospinous fixation"],
  ["sacrocolpopexy", "sacral colpopexy", "lsc", "laparoscopic sacrocolpopexy", "robotic sacrocolpopexy"],
  ["colpocleisis", "obliterative", "lefort", "le fort"],
  ["hysteropexy", "uterine preservation", "uterine sparing"],
  ["pessary", "pessaries"],
  ["mesh exposure", "mesh erosion", "mesh extrusion", "mesh complication", "mesh complications"],
  // Bowel
  ["fi", "fecal incontinence", "anal incontinence", "bowel incontinence", "accidental bowel leakage", "abl"],
  ["dd", "defecatory dysfunction", "obstructed defecation"],
  ["rectal prolapse", "procidentia"],
  ["oasis", "obstetric anal sphincter injury", "obstetric anal sphincter injuries", "perineal laceration", "sphincter laceration"],
  ["rvf", "rectovaginal fistula", "rectovaginal fistulas"],
  // Fistula, diverticulum, injury
  ["vvf", "vesicovaginal fistula", "vesicovaginal fistulas"],
  ["ugf", "ug fistula", "urogenital fistula", "genitourinary fistula"],
  ["ud", "urethral diverticulum", "urethral diverticula", "diverticulum", "diverticula"],
  ["ureteral injury", "ureter injury", "ureteric injury"],
  ["bladder injury", "cystotomy"],
  // Office procedures and testing
  ["uds", "urodynamics", "urodynamic", "cmg", "cystometrogram", "cystometry"],
  ["upp", "urethral pressure profile"],
  ["vlpp", "valsalva leak point pressure", "leak point pressure", "alpp"],
  ["emg", "electromyography"],
  ["cystoscopy", "cystourethroscopy", "cysto"],
  ["snm", "sacral neuromodulation", "sacral nerve stimulation", "sns", "interstim"],
  ["ptns", "ptnm", "percutaneous tibial nerve stimulation", "tibial nerve stimulation"],
  ["botox", "onabotulinumtoxina", "onabota", "botulinum toxin"],
  ["pfmt", "pelvic floor muscle training", "kegel", "kegels", "pelvic floor exercises"],
  ["pfpt", "pelvic floor physical therapy"],
  // Slings
  ["mus", "midurethral sling", "mid urethral sling", "sling", "tvt", "tension free vaginal tape", "tot", "transobturator tape", "retropubic sling", "transobturator sling"],
  ["burch", "colposuspension"],
  // Imaging
  ["mri", "magnetic resonance imaging", "mr defecography", "dynamic mri"],
  ["ultrasound", "ultrasonography", "sonography", "endoanal ultrasound", "eaus"],
  ["ct", "computed tomography", "ct urogram", "ct urography", "ctu"],
  ["vcug", "voiding cystourethrogram"],
  ["defecography", "defecogram"],
  // Vulvovaginal, hormones, gender-affirming care
  ["gsm", "genitourinary syndrome of menopause", "vaginal atrophy", "atrophic vaginitis", "vulvovaginal atrophy", "vva"],
  ["vaginal estrogen", "topical estrogen", "local estrogen"],
  ["hrt", "mht", "hormone therapy", "menopausal hormone therapy", "hormone replacement"],
  ["gender affirming", "gender affirmation", "transgender", "transmasculine", "transfeminine"],
  // Pain
  ["cpp", "chronic pelvic pain", "pelvic pain"],
  ["myofascial pelvic pain", "levator myalgia", "pelvic floor myalgia", "hypertonic pelvic floor", "high tone pelvic floor"],
  // Perioperative
  ["eras", "enhanced recovery after surgery", "enhanced recovery"],
  ["vte", "venous thromboembolism", "dvt", "deep vein thrombosis", "pulmonary embolism"],
  ["ssi", "surgical site infection"],
  // Neurology and systems
  ["ms", "multiple sclerosis"],
  ["sci", "spinal cord injury"],
  ["cns", "central nervous system"],
  ["gu", "genitourinary"],
  ["gi", "gastrointestinal"],
  ["msk", "musculoskeletal"],
  ["osa", "obstructive sleep apnea"],
  // Outcomes, research, quality
  ["pfd", "pelvic floor disorders", "pelvic floor disorder", "pelvic floor dysfunction"],
  ["pfdi", "pelvic floor distress inventory"],
  ["pfiq", "pelvic floor impact questionnaire"],
  ["pro", "pros", "patient reported outcome", "patient reported outcomes"],
  ["qol", "quality of life"],
  ["qi", "quality improvement"],
  ["pdsa", "plan do study act"],
  ["rct", "randomized controlled trial", "randomized trial"],
  ["ebm", "evidence based medicine", "evidence based practice"],
  // Societies
  ["aua", "american urological association"],
  ["augs", "american urogynecologic society", "urogynecologic society"],
  ["sufu", "society of urodynamics"],
  ["acog", "american college of obstetricians and gynecologists"],
  ["ics", "international continence society"],
  ["iuga", "international urogynecological association"],
  ["fpmrs", "female pelvic medicine", "urogynecology", "urogynecologic"],
];
